### ISSUE TITLE
Mod Request: /dank/null

### ISSUE THREAD

**Issue by mmonaghan** [HNGamingUK/HNG-Pack#2]
Seeing as 1.12 doesn't have OpenBlocks, an equivalent of the /dev/null would be incredibly useful, /dank/null ( https://www.curseforge.com/minecraft/mc-mods/dank-null ) fulfills that purpose but also allows for multiple items types in a singular /dank/null.

**Comment by HNGamingUK** [comment]
Added /dank/null in v1.0.3 of the HNG Pack
